on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:
    -  uses: actions/checkout@v1     
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |   
        Invoke-AzVmRunCommand `
             -ResourceGroupName "test" `
             -VMName "test" `
             -CommandId "RunPowerShellScript" `
             -ScriptPath "./test.ps1"
