on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:
    -  uses: actions/checkout@v1     
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |   
         $fileUris = @("https://raw.https://github.com/sree4795/Testing.git/test.ps1")
         $protectedSettings = @{
                "fileUris" = $fileUris
                "commandToExecute" = "powershell -ExecutionPolicy Unrestricted -File test.ps1"    
                 }
