name: Windows

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        SSHKEY: ${{ secrets.SSH_GITHUB }}
    - run: ssh -T git@github.com || true
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        ORIGIN: ${{ secrets.HOST }}
        SSHKEY: ${{ secrets.SSH_SERVER }}
        NAME: production
        PORT: ${{ secrets.PORT }}
        USER: azadmin
    - run: 
         New-Item -Path 'C:\Test Folder' -ItemType Directory
